### PR TITLE
Copy directories to destination dir

### PR DESCRIPTION
**Pull request by pscheit**
Hi there,

thank your for this gem. I tried to extend it a little bit to use cp_r to copy directories recursively. This is not the wildcard-solution you have suggested but maybe a good start.
the convention is: when a path ends with a slash on the source side it is considered as a directory.

please for give me for rude mistakes - this is my first ruby contribution.

best regards
philipp

### CODE REVIEW

**Comment by pscheit** [comment]
should I / must I increment the version?

**Comment by basvodde** [comment]
Uhm isn't the copy recursive done automatically with the FileUtils copy? If not, why not always use cp_r?

ps. The wildcard support is already implemented :) I did it myself after I wrote the README but actually never updated the README :(

**Comment by pscheit** [comment]
I think i tested it with a directory and it says: "this is a directory cannot copy". I could not find an info, that the dir is copied recursively with copy() in the docs. But of course, you can prove me wrong :)
Does the FileUtils.copy support wildcards? Otherwise I cannot see the wildcard behaviour.

**Comment by basvodde** [comment]
I'll double check on the behavior of copy. Otherwise, would just using cp_r all the time work?

The wildcard behavior is in here: prepare_files_to_deploy (Dir.glob)

**Comment by pscheit** [comment]
oh i really did not get this. Well then the fix is superfluous because you can use dir/\* and dir for copying.

**Comment by basvodde** [comment]
Ah, still, I think being able to copy a dir with just stating the dir would be a good thing IMHO.

**Comment by pscheit** [comment]
cp_r sounds like that string of file is not okay, but list of file:

```
Copies src to dest. If src is a directory, this method copies all its contents recursively. If dest is a directory, copies src to dest/src.

src can be a list of files.
```

**Comment by basvodde** [comment]
Reading the documentation, I think we can just replace cp with cp_r and get rid of the additional check if it is a directory or not ?

**Comment by pscheit** [comment]
i really don't know for sure :)

**Comment by basvodde** [comment]
Sorry for the delay on this. I changed the Fileutils from copy to cp_r, which I think would resolve this and make the rest of the pull request not needed. Do you want to check that out?

**Comment by pscheit** [comment]
never mind (for the delay). Yep that fixes it

**Pull request closed without merging**
